runtime: python36
entrypoint: gunicorn -b :$PORT app:server
# threadsafe: true # not supported in python3.6
#automatic_scaling:
#    min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
#    max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
#    min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
#    max_pending_latency: automatic

runtime_config:
    python_version: 3.6

handlers:
- url: /images
  static_dir: images

- url: /annotations
  static_dir: annotations

- url: .*
  script: app.py

resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
