runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
    python_version: 3.6

handlers:
- url: /images
  static_dir: images

- url: /annotations
  static_dir: annotations

- url: .*
  script: app.py

resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
