runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 36

handlers:
- url: /images/*
  static_dir: images

- url: /annotations/*
  static_dir: annotations

- url: .*
  script: app.py
