baseURL = "https://dychi.github.io/dash-action-segmentation-demo/"
languageCode = "ja"
title = "Document for dash-segmentation demo app"
theme = "hugo-theme-learn"
publishDir = "../docs"
contentDir = "content"
layoutDir = "layouts"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/dychi/dash-action-segmentation-demo"
weight = 10