baseURL = "https://dychi.github.io/dash-action-segmentation-demo/"
languageCode = "ja"
title = "Document for dash-segmentation demo app"
theme = "hugo-theme-learn"
publishDir = "../docs"
contentDir = "content"
layoutDir = "layouts"
