baseURL = "https://dychi.github.io/dash-action-segmentation-demo/docs/"
languageCode = "ja"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
publishdir = "docs"
contentdir = "content"
layoutdir = "layouts"
